openapi: '3.0.3'
info:
  title: Belajar Rest API
  version: '1.0'
servers:
  - url: http://localhost:3000

components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string

paths:
  /users:
    get:
      description: 'endpoint untuk mendapatkan semua data user'
      parameters: []
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
          description: Server Gagal
        '403':
          description: Tidak diizinkan

    post:
      description: 'endpoint untuk menambahkan user baru'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: Berhasil menambahkan user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '500':
          description: Server Gagal
        '403':
          description: Tidak diijinkan

  /users/{id}:
    get:
      description: 'endpoint untuk mendapatkan data user berdasarkan id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '404':
          description: User tidak ditemukan
        '500':
          description: Server Gagal

    delete:
      description: 'endpoint untuk menghapus data user berdasarkan id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil dihapus
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: User tidak ditemukan
        '500':
          description: Server Gagal

    put:
      description: 'endpoint untuk mengubah data user berdasarkan id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                age:
                  type: integer
                createdAt:
                  type: string
                updatedAt:
                  type: string
      responses:
        '200':
          description: Berhasil diupdate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '404':
          description: User tidak ditemukan
        '400':
          description: Request tidak valid
        '500':
          description: Server Gagal
